# Generated by Django 5.2.7 on 2025-10-01 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('autore', models.CharField(max_length=40)),
                ('data_pubblicazione', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prestito', models.DateField()),
                ('data_scadenza', models.DateField()),
                ('data_restituzione', models.DateField(blank=True, null=True)),
                ('catalogo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrestitiLibro.catalogo')),
                ('utente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
