# Generated by Django 5.2.7 on 2025-10-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrestitiLibro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='disponibilità',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prestiti',
            name='restituito',
            field=models.BooleanField(default=False),
        ),
    ]
