# Generated by Django 5.2.7 on 2025-10-03 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrestitiLibro', '0002_catalogo_disponibilità_prestiti_restituito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valutazione', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commento', models.TextField(blank=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('catalogo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrestitiLibro.catalogo')),
                ('utente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
