# Generated by Django 5.2.7 on 2025-10-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrestitiLibro', '0003_recensione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestiti',
            name='data_prestito',
            field=models.DateField(auto_now_add=True),
        ),
    ]
