# Generated by Django 5.2.7 on 2025-10-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrestitiLibro', '0004_alter_prestiti_data_prestito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'permissions': [('can_borrow_book', 'Può prendere in prestito libri'), ('can_manage_loans', 'Può gestire i prestiti')]},
        ),
        migrations.AlterModelOptions(
            name='prestiti',
            options={'permissions': []},
        ),
    ]
